// prod.js
module.exports = {
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  MONGO_DB_CONNECTION: process.env.MONGO_DB_CONNECTION,
  COOKIE_KEY: process.env.COOKIE_KEY,
  STRIPE_PUBLISHABLE_KEY: process.env.STRIPE_PUBLISHABLE_KEY,
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
  SEND_GRID_KEY: process.env.SEND_GRID_KEY,
  SEND_GRID_ADDITIONAL_KEY: process.env.SEND_GRID_ADDITIONAL_KEY,
  REDIRECT_DOMAIN: process.env.REDIRECT_DOMAIN,
  TELEGRAM_TOKEN: process.env.TELEGRAM_TOKEN
};
